Update ci_dw.yml

diff --git a/.github/workflows/ci_dw.yml b/.github/workflows/ci_dw.yml
--- a/.github/workflows/ci_dw.yml
+++ b/.github/workflows/ci_dw.yml
@@ -9,11 +9,21 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+    - name: Debug Secrets
+      run: echo "API_URL_1_INO: ${{ secrets.API_URL_1_INO }}\nAPI_URL_2_NEG: ${{ secrets.API_URL_2_NEG }}"
 
-    - name: Set up shell script permissions
-      run: chmod +x ./run_api_requests.sh
+    - name: Make API request to get_data_organized/192959544
+      run: |
+        curl -s -o /dev/null -w "%{http_code}" "${{ secrets.API_URL_1_INO }}"
+        if [ $? -ne 0 ]; then
+          echo "Failed to fetch ${{ secrets.API_URL_1_INO }}"
+          exit 1
+        fi
 
-    - name: Make API requests
-      run: ./run_api_requests.sh "${{ secrets.API_URL_1_INO }}" "${{ secrets.API_URL_2_NEG }}"
+    - name: Make API request to get_data_organized/174940580
+      run: |
+        curl -s -o /dev/null -w "%{http_code}" "${{ secrets.API_URL_2_NEG }}"
+        if [ $? -ne 0 ]; then
+          echo "Failed to fetch ${{ secrets.API_URL_2_NEG }}"
+          exit 1
+        fi
